export const INIT_USERS = [
  {
    id: "akujbenvr",
    username: "admin",
    password: "admin",
    email: "admin1@example.com",
    firstName: "Yerjan",
    lastName: "Turarov",
    imgSrc: "https://cdn-icons-png.flaticon.com/512/149/149071.png",
    birthday: new Date("Feb 24 1998"),
    isSuperUser: true,
    movies: [
      { id: "jasdhkhadjsj", status: "finished", isFavorite: true },
      { id: "arehsfdbesr", status: "finished", isFavorite: false },
      { id: "xklnjkna", status: "willWatch", isFavorite: false },
    ],
  },
  {
    id: "akujsdrobin",
    username: "moderator",
    password: "moderator",
    email: "admin2@example.com",
    firstName: "Flavius",
    lastName: "Bejan",
    imgSrc: "",
    birthday: new Date("Feb 24 1998"),
    isSuperUser: true,
    movies: [
      { id: "jasdhkhadjsj", status: "finished", isFavorite: true },
      { id: "arehsfdbesr", status: "finished", isFavorite: false },
      { id: "xklnjkna", status: "willWatch", isFavorite: false },
    ],
  },
  {
    id: "aktheyurobin",
    username: "marriska",
    password: "marriska",
    firstName: "Marriska",
    lastName: "Fernandes",
  },
  {
    id: "aktsgfbnyt54",
    username: "eric",
    password: "eric",
    firstName: "Eric",
    lastName: "Marchen",
  },
  {
    id: "te45heyurobin",
    username: "nicki",
    password: "nicki",
    firstName: "Nicki",
    lastName: "Dusse",
  },
  {
    id: "akey45fbty52robin",
    username: "keith",
    password: "keith",
    firstName: "Keith",
    lastName: "Garlington",
  },
  {
    id: "aoinarobe21obin",
    username: "liz",
    password: "liz",
    firstName: "Liz",
    lastName: "Miller",
  },
  {
    id: "aouhiubv502in",
    username: "jonathan",
    password: "jonathan",
    firstName: "Jonathan",
    lastName: "Sim",
  },
  {
    id: "a235dfvw1",
    username: "cory",
    password: "cory",
    firstName: "Cory",
    lastName: "Woodroof",
  },
  {
    id: "fgbghe641drf",
    username: "robert",
    password: "robert",
    firstName: "Robert",
    lastName: "Roten",
  },
];
