//comment
export const INIT_MOVIES = [
  {
    id: "arehsfdbesr",
    title: "Thor: Love and Thunder",
    description:
      "Thor enlists the help of Valkyrie, Korg and ex-girlfriend Jane Foster to fight Gorr the God Butcher, who intends to make the gods extinct.",
    reviewIds: ["ionvrkjna", "inilsnvkjnr", "aegikldffnvela"],
    imgSrc:
      "https://m.media-amazon.com/images/M/MV5BYmMxZWRiMTgtZjM0Ny00NDQxLWIxYWQtZDdlNDNkOTEzYTdlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
    tags: ["action", "adventure", "fantasy", "comedy", "movie"],
    releaseDate: "Dec 12, 2021",
    duration: 148,
    casts: [
      "marisa tomei",
      "martin starr",
      "jamie foxx",
      "j.K. simmons",
      "harry holland",
    ],
    country: "germany",
  },
  {
    id: "jasdhkhadjsj",
    title: "Spider-Man: No Way Home",
    description:
      "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    reviewIds: [],
    imgSrc:
      "https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_FMjpg_UX1000_.jpg",
    tags: ["action", "adventure", "fantasy", "comedy", "movie"],
    releaseDate: "Dec 17, 2021",
    duration: 148,
    casts: [
      "marisa tomei",
      "martin starr",
      "jamie foxx",
      "J.K. Simmons",
      "Harry Holland",
    ],
    country: "united kingdom",
  },
  {
    id: "xklnjkna",
    title: "Thirteen Lives",
    description:
      "A rescue mission is assembled in Thailand where a group of young boys and their soccer coach are trapped in a system of underground caves that are flooding.",
    reviewIds: ["inbevibeaw"],
    imgSrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRX0XPUKm_WAay40EiZSQiRugaM54m-KITTQe3BTV9Nu3DKGoe",
    tags: ["drama", "movie"],
    releaseDate: "Jul 29, 2022",
    duration: 144,
    casts: [
      "marisa Tomei",
      "martin Starr",
      "jamie Foxx",
      "J.K. Simmons",
      "Harry Holland",
    ],
    country: "United States of America",
  },
  {
    id: "qwqweiqwpo",
    title: "TROLL",
    description:
      "Deep inside the mountain of Dovre, something gigantic awakens after being trapped for a thousand years. Destroying everything in its path, the creature is fast approaching the capital of Norway. But how do you stop something you thought only existed in Norwegian folklore? ",
    reviewIds: ["iubjbvoijpwrvr", "iugebkjvaiue"],
    imgSrc:
      "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQHvaRbcer1ya3BIvzWC73YG3GxuPrQUFNhiJqGRMm74qpAL8km",
    tags: ["action", "adventure", "fantasy", "mystery", "thriller", "movie"],
    releaseDate: "Dec 1, 2022 ",
    duration: 103,
    casts: [
      "Marisa Tomei",
      "Martin Starr",
      "Jamie Foxx",
      "J.K. Simmons",
      "Harry Holland",
    ],
    country: "United States of America",
  },
  //from flavius
  {
    id: "zxcjkhjkdas",
    title: "Puss in Boots: The Last Wish",
    description:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives. ",
    reviewIds: [""],
    imgSrc: "https://image.tmdb.org/t/p/w500//kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    tags: ["animation", "adventure", "comedy", "movie"],
    releaseDate: "Dec 21, 2022 ",
    duration: 100,
    casts: [
      "Antonio Banderas",
      "Harvey Guillén",
      "John Mulaney",
      "Salma Hayek",
      "Wagner Moura",
    ],
    country: "United States of America",
  },
  {
    id: "avatarjkhjkdas",
    title: "Avatar: The Way of Water",
    description:
      "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure. ",
    reviewIds: [""],
    imgSrc: "https://image.tmdb.org/t/p/w500//t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    tags: ["action", "adventure", "fantasy", "movie"],
    releaseDate: "Dec 14, 2022 ",
    duration: 192,
    casts: [
      "Sam Worthington",
      "Sigourney Weaver",
      "Kate Winslet",
      "Joel David Moore",
      "Jemaine Clement",
    ],
    country: "United States of America",
  },
  {
    id: "violentjkhjkdas",
    title: "Violent Night",
    description:
      "When a team of mercenaries breaks into a wealthy family compound on Christmas Eve, taking everyone inside hostage, the team isn’t prepared for a surprise combatant: Santa Claus is on the grounds, and he’s about to show why this Nick is no saint.",
    reviewIds: [""],
    imgSrc: "https://image.tmdb.org/t/p/w500//1XSYOP0JjjyMz1irihvWywro82r.jpg",
    tags: ["action", "cpmedy", "crime", "movie"],
    releaseDate: "Nov 30, 2022 ",
    duration: 112,
    casts: [
      "David Harbour",
      "Beverly D'Angelo",
      "Alexis Louder",
      "Cam Gigandet",
      "André Eriksen",
    ],
    country: "United States of America",
  },
  {
    id: "M3GANjkhjkdas",
    title: "M3GAN",
    description:
      "A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece. But when the doll's programming works too well, she becomes overprotective of her new friend with terrifying results.",
    reviewIds: [""],
    imgSrc: "https://image.tmdb.org/t/p/w500//7CNCv9uhqdwK7Fv4bR4nmDysnd9.jpg",
    tags: ["horror", "sci-fi", "thriller", "movie"],
    releaseDate: "Dec 28, 2022 ",
    duration: 102,
    casts: [
      "Allison Williams",
      "Ronny Chieng",
      "Jenna Davis",
      "Jen Van Epps",
      "Millen Baird",
    ],
    country: "United States of America",
  },
  {
    id: "BlackAdamjkhjkdas",
    title: "Black Adam",
    description:
      "Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.",
    reviewIds: [""],
    imgSrc: "https://image.tmdb.org/t/p/w500//pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg",
    tags: ["action", "adventure", "fantasy", "movie"],
    releaseDate: "Oct 21, 2022 ",
    duration: 125,
    casts: [
      "Dwayne Johnson",
      "Pierce Brosnan",
      "Sarah Shahi",
      "Marwan Kenzari",
      "Jalon Christian",
    ],
    country: "United States of America",
  },
  {
    id: "Lionjkhjkdas",
    title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    description:
      "Siblings Lucy, Edmund, Susan and Peter step through a magical wardrobe and find the land of Narnia. There, they discover a charming, once peaceful kingdom that has been plunged into eternal winter by the evil White Witch, Jadis. Aided by the wise and magnificent lion, Aslan, the children lead Narnia into a spectacular, climactic battle to be free of the Witch's glacial powers forever.",
    reviewIds: [""],
    imgSrc: "https://image.tmdb.org/t/p/w500//iREd0rNCjYdf5Ar0vfaW32yrkm.jpg",
    tags: ["family", "adventure", "fantasy", "movie"],
    releaseDate: "Jul 12, 2005 ",
    duration: 148,
    casts: [
      "Tilda Swinton",
      "Anna Popplewell",
      "Jim Broadbent",
      "James Cosmo",
      "Patrick Kake",
    ],
    country: "United States of America",
  },
  {
    id: "encantojkhjkdas",
    title: "Encanto at the Hollywood Bowl",
    description:
      "A taped performance of the Encanto Live-to-Film Concert Experience at the Hollywood Bowl. The original cast puts on a miracle of a concert as they sing the favorite songs, accompanied by a full orchestra and 50 person ensemble, and the Hollywood Bowl transforms into Casita!",
    reviewIds: [""],
    imgSrc: "https://image.tmdb.org/t/p/w500//sa3Ku5yNVjp8NloWxJoI9dQjvOi.jpg",
    tags: ["family", "music", "movie"],
    releaseDate: "Dec 28, 2022 ",
    duration: 45,
    casts: [
      "Jessica Darrow",
      "Stephanie Beatriz",
      "Angie Cepeda",
      "Adassa",
      "Mauro Castillo",
    ],
    country: "United States of America",
  },
  {
    id: "knivesjkhjkdas",
    title: "Glass Onion: A Knives Out Mystery",
    description:
      "World-famous detective Benoit Blanc heads to Greece to peel back the layers of a mystery surrounding a tech billionaire and his eclectic crew of friends.",
    reviewIds: [""],
    imgSrc: "https://image.tmdb.org/t/p/w500//vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg",
    tags: ["comedy", "crime", "drama"],
    releaseDate: "Nov 23, 2022 ",
    duration: 139,
    casts: [
      "Daniel Craig",
      "Dave Bautista",
      "Kate Hudson",
      "Jessica Henwick",
      "Madelyn Cline",
    ],
    country: "United States of America",
  },
  {
    id: "firstavatarjkhjkdas",
    title: "Avatar",
    description:
      "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.",
    reviewIds: [""],
    imgSrc: "https://image.tmdb.org/t/p/w500//jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg",
    tags: ["action", "adventure", "fantasy"],
    releaseDate: "Dec 15, 2009 ",
    duration: 162,
    casts: [
      "Sam Worthington",
      "Sigourney Weaver",
      "Stephen Lang",
      "Joel David Moore",
      "Wes Studi",
    ],
    country: "United States of America",
  },
  {
    id: "womankingjkhjkdas",
    title: "The Woman King",
    description:
      "The story of the Agojie, the all-female unit of warriors who protected the African Kingdom of Dahomey in the 1800s with skills and a fierceness unlike anything the world has ever seen, and General Nanisca as she trains the next generation of recruits and readies them for battle against an enemy determined to destroy their way of life.",
    reviewIds: [""],
    imgSrc: "https://image.tmdb.org/t/p/w500//438QXt1E3WJWb3PqNniK0tAE5c1.jpg",
    tags: ["action", "drama", "history", "movie"],
    releaseDate: "Sep 16, 2022 ",
    duration: 135,
    casts: [
      "Viola Davis",
      "Lashana Lynch",
      "John Boyega",
      "Hero Fiennes Tiffin",
      "Masali Baduza",
    ],
    country: "United States of America",
  },
  {
    id: "lastclinetjkhjkdas",
    title: " The Last Client",
    description:
      "Renowned psychologist Susanne (Signe Egholm Olsen) is caught in a living nightmare when her new client (Anton Hjejle) turns out to be a wanted serial killer.",
    reviewIds: [""],
    imgSrc: "https://image.tmdb.org/t/p/w500//Agx1zaPXWiiG0wyKhuUJfinaRGJ.jpg",
    tags: ["thriller", "movie"],
    releaseDate: "Jun 20, 2022 ",
    duration: 95,
    casts: [
      "Signe Egholm Olsen",
      "Dan Zahle",
      "Anders Mossling",
      "Thalita Beltrão Sørensen",
      "Torben Svendsen",
    ],
    country: "United States of America",
  },
  {
    id: "savagejkhjkdas",
    title: " Savage Salvation",
    description:
      "Newly engaged Shelby John and Ruby Red want a fresh start after their struggles with addiction, but when Shelby discovers his beloved Ruby dead on their porch, he embarks on a vengeful killing spree of the dealers who supplied her. Armed with nothing but adrenaline and a nail gun, Shelby begins to unleash chaos on the town’s criminal underbelly, as he hunt’s down crime lord Coyote. Sheriff Church must race against the clock to put an end to Shelby's vigilante justice before the entire town descends into a bloodbath.",
    reviewIds: [""],
    imgSrc: "https://image.tmdb.org/t/p/w500//fJRt3mmZEvf8gQzoNLzjPtWpc9o.jpg",
    tags: ["action", "thriller", "movie"],
    releaseDate: "Dec 12, 2022 ",
    duration: 101,
    casts: [
      "Robert De Niro",
      "Willa Fitzgerald",
      "Jack Huston",
      "Meadow Williams",
      "John Malkovich",
    ],
    country: "United States of America",
  },
];
