export const INIT_USERS = [
  {
    id: "akujbenvr",
    username: "admin",
    password: "admin",
    email: "admin1@example.com",
    firstName: "Yerjan",
    lastName: "Turarov",
    imgSrc:
      "https://icatcare.org/app/uploads/2018/07/Thinking-of-getting-a-cat.png",
    birthday: new Date("Feb 24 1998"),
    createdAt: "Dec 2, 2020",
    isSuperUser: true,
    movies: [
      { id: "jasdhkhadjsj", status: "finished", isFavorite: true },
      { id: "arehsfdbesr", status: "finished", isFavorite: false },
      { id: "xklnjkna", status: "willWatch", isFavorite: false },
    ],
    // friends statuses => friend, requested
    friends: [
      {
        id: "akujsdrobin",
        status: "friend",
        createdAt: new Date("Mar 12, 2021"),
        updatedAt: new Date("Mar 15, 2021"),
      },
      {
        id: "aktheyurobin",
        status: "friend",
        createdAt: new Date("Jun 5, 2021"),
        updatedAt: new Date("Jun 6, 2021"),
      },
      {
        id: "te45heyurobin",
        status: "requested",
        createdAt: new Date("Sep 21, 2022"),
        updatedAt: new Date("Sep 21, 2022"),
      },
    ],
    notifications: [
      {
        type: "friend_request",
        createdBy: "akey45fbty52robin",
        createdAt: new Date("Dec 27, 2022"),
        isRead: false,
      },
      {
        type: "friend_acceptence",
        createdBy: "aktheyurobin",
        createdAt: new Date("Jun 6, 2021"),
        isRead: true,
      },
      {
        type: "moderator_privilage",
        createdBy: "akujsdrobin",
        createdAt: new Date("Dec 2, 2020"),
        isRead: true,
      },
    ],
  },
  {
    id: "akujsdrobin",
    username: "moderator",
    password: "moderator",
    email: "admin2@example.com",
    firstName: "Flavius",
    lastName: "Bejan",
    imgSrc: "",
    birthday: new Date("Feb 24 1998"),
    createdAt: "Dec 2, 2010",
    isSuperUser: true,
    movies: [
      { id: "jasdhkhadjsj", status: "finished", isFavorite: true },
      { id: "arehsfdbesr", status: "finished", isFavorite: false },
      { id: "xklnjkna", status: "willWatch", isFavorite: false },
    ],
    friends: [
      {
        id: "akujbenvr",
        status: "friend",
        createdAt: new Date("Mar 12, 2021"),
        updatedAt: new Date("Mar 15, 2021"),
      },
    ],
  },
  {
    id: "aktheyurobin",
    username: "marriska",
    password: "marriska",
    firstName: "Marriska",
    lastName: "Fernandes",
    createdAt: "Dec 2, 2018",
    friends: [
      {
        id: "akujbenvr",
        status: "friend",
        createdAt: new Date("Jun 5, 2021"),
        updatedAt: new Date("Jun 6, 2021"),
      },
    ],
  },
  {
    id: "aktsgfbnyt54",
    username: "eric",
    password: "eric",
    firstName: "Eric",
    lastName: "Marchen",
    createdAt: "Dec 2, 2015",
  },
  {
    id: "te45heyurobin",
    username: "nicki",
    password: "nicki",
    firstName: "Nicki",
    lastName: "Dusse",
    createdAt: "Dec 2, 2005",
    notifications: [
      {
        type: "friend_request",
        createdBy: "akujbenvr",
        createdAt: new Date("Dec 27, 2022"),
        isRead: false,
      },
    ],
  },
  {
    id: "akey45fbty52robin",
    username: "keith",
    password: "keith",
    firstName: "Keith",
    lastName: "Garlington",
    createdAt: "Dec 2, 2008",
    friends: [
      {
        id: "akujbenvr",
        status: "requested",
        createdAt: new Date("Dec 27, 2022"),
        updatedAt: new Date("Dec 27, 2022"),
      },
    ],
  },
  {
    id: "aoinarobe21obin",
    username: "liz",
    password: "liz",
    firstName: "Liz",
    lastName: "Miller",
    createdAt: "Dec 2, 2017",
  },
  {
    id: "aouhiubv502in",
    username: "jonathan",
    password: "jonathan",
    firstName: "Jonathan",
    lastName: "Sim",
    createdAt: "Dec 2, 2015",
  },
  {
    id: "a235dfvw1",
    username: "cory",
    password: "cory",
    firstName: "Cory",
    lastName: "Woodroof",
    createdAt: "Dec 2, 2009",
  },
  {
    id: "fgbghe641drf",
    username: "robert",
    password: "robert",
    firstName: "Robert",
    lastName: "Roten",
    createdAt: "Dec 2, 2019",
  },
];
